// <auto-generated />
using System;
using DomainLayer.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180808115808_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLayer.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("EditDate");

                    b.Property<int>("RecipeId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime?>("EditDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("RecipeStatus");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new { Id = 1, Content = "Blah", CreationDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "Blah-blah", Name = "Something", RecipeStatus = 1, UserId = 1 },
                        new { Id = 2, Content = "Blah", CreationDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), DeleteDate = new DateTime(2018, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "Blah-blah", EditDate = new DateTime(2018, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "SomethingElse", RecipeStatus = 2, UserId = 1 },
                        new { Id = 3, Content = "Blah", CreationDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "Blah-blah", EditDate = new DateTime(2018, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "SomethingElseElse", RecipeStatus = 1, UserId = 2 }
                    );
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.RecipeTag", b =>
                {
                    b.Property<int>("RecipeId");

                    b.Property<int>("TagId");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Content");

                    b.HasIndex("Content");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("PasswordHash");

                    b.Property<int>("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");


                    b.HasAlternateKey("Username");

                    b.HasIndex("Email");

                    b.HasIndex("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, CreationDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "user1@example.com", PasswordHash = "yfhrhr838319-sdkkie92-sdew2", Role = 2, Username = "user1" },
                        new { Id = 2, CreationDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "user2@example.com", PasswordHash = "yfhrhr838319-sdkkie92-sdew2", Role = 1, Username = "user2" }
                    );
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("Avatar");

                    b.Property<bool>("IsMuted");

                    b.Property<int>("UserStatus");

                    b.HasKey("UserId");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new { UserId = 1, Avatar = "https://kek.com/kek.jpg", IsMuted = false, UserStatus = 1 },
                        new { UserId = 2, Avatar = "https://kek.com/kek.jpg", IsMuted = false, UserStatus = 1 }
                    );
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RecipeId");

                    b.Property<int?>("UserId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");

                    b.HasData(
                        new { Id = 1, RecipeId = 1, UserId = 1, Value = 5 },
                        new { Id = 2, RecipeId = 1, UserId = 2, Value = 2 }
                    );
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.Comment", b =>
                {
                    b.HasOne("DomainLayer.Models.Entities.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DomainLayer.Models.Entities.UserProfile", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.Recipe", b =>
                {
                    b.HasOne("DomainLayer.Models.Entities.UserProfile", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.RecipeTag", b =>
                {
                    b.HasOne("DomainLayer.Models.Entities.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DomainLayer.Models.Entities.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.UserProfile", b =>
                {
                    b.HasOne("DomainLayer.Models.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("DomainLayer.Models.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Models.Entities.Vote", b =>
                {
                    b.HasOne("DomainLayer.Models.Entities.Recipe", "Recipe")
                        .WithMany("Votes")
                        .HasForeignKey("RecipeId");

                    b.HasOne("DomainLayer.Models.Entities.UserProfile", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
